version: '3.3'
services:
    db:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
          - db_data:/var/lib/mysql
    php:
        build:
            context: .
        ports:
            - "9000:9000"
        volumes:
            - ./api:/var/www/api:cached
        depends_on:
            - db
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./api:/var/www/api:cached
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"  # Web UI port
            - "1025:1025"  # SMTP port
    coverage:
        image: nginx:latest
        ports:
            - "5001:80"
        volumes:
            - ./api/coverage:/usr/share/nginx/html:cached
        depends_on:
            - db
    vue:
        image: node:alpine
        command: tail -F /dev/null
        working_dir: /usr/src/app
        volumes:
            - ./vue:/usr/src/app
    react:
        image: node:alpine
        command: tail -F /dev/null
        working_dir: /usr/src/app
        volumes:
            - ./react:/usr/src/app
volumes:
  db_data: